Title: HyperNav
Logo: "<img src='https://adamantica.com/projects/hyper-nav/icon.svg' style='width: 3.2rem; margin-right: 0.4rem'><span style='font-weight: normal; font-size: 2.2rem; font-family: Negatronic;'>HyperNav</span>"
Version: 1.0.0